####GENERAL CONFIGURATION####
POLAR_SCENARIO = 3
RESULTS_PATH = './simulationResults/'

####CLIGHTNING CONFIGURATION####
CLIGHTNING_USER = 'clightning'


####LND CONFIGURATION####
LND_USER = 'lnd'


####ECLAIR CONFIGURATION####
ECLAIR_USER = 'eclair'